### ISSUE TITLE
Use Ogre::Codec instead of Freeimage

### ISSUE THREAD

**Issue by paroj** [giogix2/PlanetGenerator#9]
using `Ogre::Codec::getCodec("png")->encodeToFile(..)` instead of freeimage directly would allow using a different implementation (like STBI in 1.10) and remove the freeimage dependency.

**Comment by latami** [comment]
It seems that your way would require running Ogre-engine (raises exception and complains of no registered codecs available when engine is not running). It would be nice if that could be avoided.

**Comment by paroj** [comment]
just create a Root without a RenderSystem and without plugins like `Ogre::Root root("");` if Root::getSingletonPtr() == NULL

**Comment by latami** [comment]
For some reason

  Ogre::Root root("");
  Ogre::FreeImageCodec::startup();

is not enough. Still gets "no codecs registered".

**Comment by paroj** [comment]
strange - works with here with 1.10

also the part
Ogre::FreeImageCodec::startup();

is superficual and should throw something like "ItemIdentityException: jpeg already has a registered codec."

**Comment by latami** [comment]
I guess 1.9 and 1.10 differ in behaviour.

with 1.9 Ogre::FreeImageCodec::startup(); just printed some info to the terminal (Same libfreeimage-related lines Ogre prints when it is started to render stuff).

I'll retry once distributions have 1.10 in their repos.

**Comment by paroj** [comment]
no, 1.9 and 1.10 should behave the same:
1. the freeimage codec registers in startup: https://github.com/OGRECave/ogre/blob/v1-9/OgreMain/src/OgreFreeImageCodec.cpp#L125
2. it throws if the codec already exists: https://github.com/OGRECave/ogre/blob/v1-9/OgreMain/include/OgreCodec.h#L86
3. Root already calls startup: https://github.com/OGRECave/ogre/blob/v1-9/OgreMain/src/OgreRoot.cpp#L237

**Comment by latami** [comment]
Oh yeah, didn't notice it before, Ogre printed libfreeimage-related lines twice.

But Ogre insists that no codecs are registered for 'png'. Saving image works fine if running root is rendering the planet.

**Comment by latami** [comment]
Eh, is this supposed to happen. :D

Ogre::Root root(""); --> Doesn't register codecs

Ogre::Root *root;
root = new Ogre::Root(""); --> Works like a charm

**Comment by latami** [comment]
Oh shoot, my bad. Ogre::Root root(""); was visible only inside if-block.

**Comment by latami** [comment]
Thanks, issue addressed and closed.
